name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      
      - name: Install GoReleaser
        run: |
          go install github.com/goreleaser/goreleaser/v2@v2.7.0
          echo "$HOME/go/bin" >> $GITHUB_PATH
          goreleaser --version
      
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: goreleaser release --clean
      
      - name: List dist directory contents
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          find dist -name "*.rb" || echo "No .rb files found"
      
      - name: Upload GoReleaser artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goreleaser-artifacts
          path: dist/
  
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Extract version tag
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            raufzer/golaunch-cli-docker:${{ steps.extract_tag.outputs.tag_name }}
            raufzer/golaunch-cli-docker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  update-homebrew-tap:
    name: Update Homebrew Tap
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    
    steps:
      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v4
        with:
          repository: raufzer/homebrew-golaunch-cli
          token: ${{ secrets.TOKEN }}
          path: homebrew-tap
      
      - name: Download GoReleaser artifacts
        uses: actions/download-artifact@v4
        with:
          name: goreleaser-artifacts
          path: dist/
      
      - name: List downloaded artifacts
        run: |
          echo "Contents of dist directory after download:"
          ls -la dist/
          find dist -name "*.rb" || echo "No .rb files found in dist"
      
      - name: Copy Homebrew Formula from GoReleaser Artifacts
        run: |
          mkdir -p homebrew-tap/Formula

          RB_FILE=$(find dist -name "*.rb" | head -n 1)
          
          if [ -n "$RB_FILE" ]; then
            echo "Found .rb file: $RB_FILE"
            cp "$RB_FILE" homebrew-tap/Formula/golaunch.rb
            echo "Copied $RB_FILE to homebrew-tap/Formula/golaunch.rb"
          else
            echo "No .rb files found in dist directory"
            exit 1
          fi
          
          cd homebrew-tap
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "feat: update golaunch to ${{ github.ref_name }}"
            git push
          fi