name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install GoReleaser
        run: |
          go install github.com/goreleaser/goreleaser@v2.7.0
          echo "$HOME/go/bin" >> $GITHUB_PATH
          goreleaser --version

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: goreleaser release --clean

  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract version tag
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            raufzer/golaunch-cli-docker:${{ steps.extract_tag.outputs.tag_name }}
            raufzer/golaunch-cli-docker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-homebrew-tap:
    name: Update Homebrew Tap
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write

    steps:
      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v4
        with:
          repository: raufzer/homebrew-golaunch-cli
          token: ${{ secrets.TOKEN }}
          path: homebrew-tap

      - name: Copy Homebrew Formula from GoReleaser Artifacts
        run: |
          cp dist/golaunch.rb homebrew-tap/Formula/ 
          cd homebrew-tap
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/golaunch.rb
          git commit -m "feat: update golaunch to ${{ github.ref_name }}"
          git push
